version: '3.8'
services:
  backend:
    container_name: backend_3
    build: ./backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    links:
      - db
    security_opt: 
      - seccomp=./chrome.json
  db:
    container_name: db_3
    image: mongo:latest
    ports:
      - "27018:27017" #  only for testing
    volumes:
      - ./mongodata:/data/db
    restart: always
