version: '3.8'
services:
  backend:
    container_name: backend_5
    build: ./backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always
    security_opt: 
      - seccomp=./chrome.json

